### ISSUE TITLE
[Development] Front-end: User interface

### ISSUE THREAD

**Issue by minayu416** [york730/horse-race#3]
**WIP**

## TODO List

- [x] Develop interface by HTML, JS, CSS
- [x] Design form to input data from users
- [x] Call APIs (axios/fetch API) + Error handling
- [x] Handle response and render back to interface
- [x] Styling

## Technology:
- Numeric Stepper -> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number (Don't need to write by ownself) (Can set max and min)
- https://stackoverflow.com/questions/45396280/customizing-increment-arrows-on-input-of-type-number-using-css
- Cool UI Lib: https://uiverse.io/?fbclid=IwZXh0bgNhZW0CMTEAAR0F3MN_XP-4wgCt28TLa-VY68gztBc1gtIGwPm-qR29xFx1rAB6v-EZ5OQ_aem_w_YexvcP2h_9KQXC9d06lA

## Figma
<img width="300" alt="Screenshot 2024-09-16 at 12 59 03 PM" src="https://github.com/user-attachments/assets/cd1bb06e-2ca7-4d84-9ca0-f4a1a4abc799">
<img width="300" alt="Screenshot 2024-09-16 at 12 59 12 PM" src="https://github.com/user-attachments/assets/a3e94d57-29df-49fd-968b-63013e1f4ba6">

**Comment by minayu416** [comment]
#2 

## Test API
- GET method for testing without Params: https://playground-eight-psi.vercel.app/test/predictor/
- POST method with body: https://playground-eight-psi.vercel.app/api/predictor/

Sample:

```json
{
    "data": {
        "一號": 
            [[3,4], [0,0,0,0,0,0], 4000], 
        "二號": 
            [[1,2,6], [0,0,0,0,0,0], 10000], 
        "三號": 
            [[3,5,6], [0,0,0,0,0,0], 100000], 
        "四號": 
            [[4,5], [0,0,0,0,0,0], 20000]
    }
}

```

~~remove original Figma exported HTML code~~
