### ISSUE TITLE
[Release] Final Result

### ISSUE THREAD

**Issue by minayu416** [york730/horse-race#4]
## TODO List

- [ ] Front-end: Deploy to Github.
- [ ] Back-end: Deploy to Vercel. 
- [ ] Back-end: Add Github page host url into flask CORS and re-deploy again.
- [ ] Front-end: Change API request url based on vercel given domain and re-deploy again.
- [ ] Test: integration testing and data & algorithm verification.
- [ ] Organize it can be part of portfolio for future interviewers.
    - [ ] README 

#5 

## Related Issues:
#1 
#2 
#3
